=== arsenykot/Votings/DOC.XSD
<?xml version="1.0" encoding="utf-8"?>
<xs:schema targetNamespace="." xmlns="." xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:complexType name="arg">
    <xs:sequence>
      <xs:element name="name" type="xs:string"/>
      <xs:element name="type" type="xs:string"/>
      <xs:element name="desc" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>



  <xs:complexType name="method">
    <xs:sequence>
      <xs:element name="name" type="xs:string"/>
      <xs:element name="desc" type="xs:string" minOccurs="0"/>
      <xs:element name="arg" type="arg" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element name="ret" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="xmltag">
    <xs:sequence>
      <xs:element name="name" type="xs:string"/>
      <xs:element name="desc" type="xs:string" minOccurs="0"/>
      <xs:element name="arg" type="arg" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="table">
    <xs:sequence>
      <xs:element name="name" type="xs:string"/>
      <xs:element name="header" type="xs:string"/>
      <xs:element name="row" type="xs:string" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>



  <xs:complexType name="docfile">
    <xs:sequence>
      <xs:element name="path" type="xs:string"/>
      <xs:element name="title" type="xs:string"/>
      <xs:element name="desc" type="xs:string" minOccurs="0"/>
      <xs:element name="method" type="method" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element name="xmltag" type="xmltag" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element name="table" type="table" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="docfolder">
    <xs:sequence>
      <xs:element name="path" type="xs:string"/>
      <xs:element name="title" type="xs:string"/>
      <xs:element name="desc" type="xs:string" minOccurs="0"/>
      <xs:element name="file" type="docfile" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element name="folder" type="docfolder" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>



  <xs:element name="docs">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="path" type="xs:string"/>
        <xs:element name="title" type="xs:string"/>
        <xs:element name="desc" type="xs:string" minOccurs="0"/>
        <xs:element name="folder" type="docfolder" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== arsenykot/Votings/docs.xml
<?xml version="1.0" encoding="utf-8"?>
<docs xmlns="." xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation=". doc/DOC.XSD">
    <path>doc</path>
    <title>Корень документации</title>
    <folder><path>api</path>
        <title>Корень документации API</title>
        <file><path>auth</path>
            <title>Эндпоинты, связанные с автозирацией</title>
            <endpoint><path>api/login</path>
                <method>POST</method>
                <desc>Попытаться войти в систему с указанным именем пользователя и паролем</desc>
                <arg><name>username</name>
                    <type>str</type>
                    <desc>Имя пользователя</desc>
                </arg>
                <arg><name>password</name>
                    <type>str</type>
                    <desc>Пароль</desc>
                </arg>
                <resp><code>400</code><data>BADREQUEST</data>
                    <when>Недостаточно аргументов</when>
                </resp>
                <resp><code>403</code><data>BADCREDENTIALS</data>
                    <when>Переданные имя пользователя и / или пароль неверны</when>
                </resp>
                <resp><code>200</code><data>OK</data>
                    <when>Авторизация прошла успешно</when>
                </resp>
            </endpoint>
            <endpoint><path>api/logout</path>
                <method>GET / POST</method>
                <desc>Выйти из аккаунта пользователя и перейти на главную страницу</desc>
            </endpoint>
        </file>
    </folder>
    <folder><path>js</path>
        <title>Корень документации JavaScript</title>
        <desc>Документация для функционала, реализованого в `/main/static/util.js` и доступного при использовании любого из шаблонов в `abc/`</desc>
        <file><path>ajax</path>
            <title>Методы AJAX</title>
            <desc>Предоставляет методы для работы с AJAX. Функционал реализован в `/main/static/util.js` в регионе `ajax`</desc>
            <method><name>ajaxQuery</name>
                <desc>Осуществляет асинхронный запрос на сервер</desc>
                <arg><name>endpoint</name>
                    <type>String</type>
                    <desc>Конечная точка API, на которую будет направлен запрос</desc>
                </arg>
                <arg><name>method</name>
                    <type>"GET"|"POST"</type>
                    <desc>Метод отправляемого запроса</desc>
                </arg>
                <arg><name>ready_callback</name>
                    <type>Function[AJAXResponse]</type>
                    <desc>Метод, который будет вызван по готовности запроса. Должен принимать фиктивный объект AJAXResponse, описанный в примечании</desc>
                </arg>
                <arg><name>data</name>
                    <type>Object</type>
                    <desc>Тело запроса в виде объекта</desc>
                </arg>
                <arg><name>error_passthrough</name>
                    <type>Boolean</type>
                    <desc>Указывает, попадёт ли ошибка в метод по готовности (по умолчанию - нет)</desc>
                </arg>
                <arg><name>httpheaders</name>
                    <type>Array[Array[String]]</type>
                    <desc>Массив пар типа `["ключ", "значение"]`, задающий HTTP-аргументы запроса. По умолчанию пуст</desc>
                </arg>
                <ret>null</ret>
            </method>
            <method><name>ajaxGet</name>
                <desc>Алиас для `ajaxQuery`, где `method="GET"`</desc>
                <argsor>endpoint, ready_callback, error_passthrough, httpheaders</argsor>
                <ret>null</ret>
            </method>
            <method><name>ajaxPost</name>
                <desc>Алиас для `ajaxQuery`, где `method="POST"`</desc>
                <argsor>endpoint, ready_callback, data, error_passthrough, httpheaders</argsor>
                <ret>null</ret>
            </method>
            <table><name>Примечание: Формат фиктивного объекта AJAXResponse</name>
                <header>Поле;Тип;Описание</header>
                <row>`status`;`Number|"error"`;HTTP-статус ответа ИЛИ "error" в случае ошибки, когда `error_passthrough` включено.</row>
                <row>`content`;`String?`;Контент ответа на запрос (не существует при `status == "error"`)</row>
                <row>`error`;`Object?`;Текст ошибки (не существует при `status != "error"`)</row>
            </table>
        </file>
        <file><path>htmlutils</path>
            <title>Утилиты для HTML</title>
            <desc>Предоставляет методы-утилиты для работы с HTML. Функционал реализован в `/main/static/util.js` в регионе `htmlutils`</desc>
            <method><name>setSpinner</name>
                <desc>Заменяет `innerHTML` элемента на спиннер с указанным текстом.</desc>
                <arg><name>element</name>
                    <type>HTMLElement</type>
                    <desc>Целевой элемент</desc>
                </arg>
                <arg><name>text</name>
                    <type>String</type>
                    <desc>Текст возле спиннера</desc>
                </arg>
                <arg><name>size</name>
                    <type>"sm"|"lg"?</type>
                    <desc>Размер спиннера. По умолчанию `sm`. См. [документацию для спиннеров](https://getbootstrap.com/docs/5.3/components/spinners/)</desc>
                </arg>
                <arg><name>type</name>
                    <type>"border"|"grow"?</type>
                    <desc>Тип анимации спиннера. По умолчанию `border`. См. [документацию для спиннеров](https://getbootstrap.com/docs/5.3/components/spinners/)</desc>
                </arg>
                <ret>null</ret>
            </method>
            <method><name>spawnToast</name>
                <desc>Создаёт уведомление-тост с указанными параметрами</desc>
                <arg><name>color</name>
                    <type>String</type>
                    <desc>Цвет уведомления-тоста. См. [Список цветов](https://getbootstrap.com/docs/5.3/customize/color/#theme-colors)</desc>
                </arg>
                <arg><name>icon</name>
                    <type>String</type>
                    <desc>Название иконки [отсюда](https://icons.getbootstrap.com/)</desc>
                </arg>
                <arg><name>content</name>
                    <type>String</type>
                    <desc>HTML-содержимое уведомления-тоста</desc>
                </arg>
                <arg><name>closeButton</name>
                    <type>Boolean</type>
                    <desc>Указывает, будет ли видна кнопка закрытия тоста. По умолчанию `false`</desc>
                </arg>
                <arg><name>container</name>
                    <type>HTMLElement</type>
                    <desc>HTML-элемент, в который требуется поместить тост. По умолчанию элемент с ID `toast-container`</desc>
                </arg>
                <ret>null</ret>
            </method>
        </file>
    </folder>
    <folder><path>py</path>
        <title>Корень документации Python</title>
        <file><path>models</path>
            <title>Django-модели</title>
        </file>
        <folder><path>util</path>
            <title>Python-утилиты</title>
            <desc>Список Python-утилит</desc>
            <file><path>requests</path>
                <title>Работа с запросами</title>
                <desc>Утилиты для работы с запросами. Описано в [main.util](/main/util.py)</desc>
                <method><name>getArgumentOr</name>
                    <desc>Возвращает значение аргумента в указанном массиве или стандартное значение при его отсутствии. Как правило имеет тип String</desc>
                    <arg><name>arr</name>
                        <type>dict[K(str), V(str)]</type>
                        <desc>Карта ключ-значение, в которой будет выполнен поиск аргумента</desc>
                    </arg>
                    <arg><name>name</name>
                        <type>K (str)</type>
                        <desc>Название параметра. Как правило имеет тип str</desc>
                    </arg>
                    <arg><name>default</name>
                        <type>Any</type>
                        <desc>Стандартное значение параметра</desc>
                    </arg>
                    <ret>V (str)|Any</ret>
                </method>
                <method><name>getGetOr</name>
                    <desc>Алиас для `getArgumentOr`, где `arr = req.GET`</desc>
                    <argsor>req, name, default</argsor>
                    <ret>V(str)|Any</ret>
                </method>
                <method><name>getPostOr</name>
                    <desc>Алиас для `getArgumentOr`, где `arr = req.POST`</desc>
                    <argsor>req, name, default</argsor>
                    <ret>V(str)|Any</ret>
                </method>
                <method><name>getSessOr</name>
                    <desc>Алиас для `getArgumentOr`, где `arr = req.session`</desc>
                    <argsor>req, name, default</argsor>
                    <ret>V(str)|Any</ret>
                </method>
            </file>
            <file><path>security</path>
                <title>Безопасность</title>
                <method><name>saltedHash</name>
                    <desc>Вычисляет солёный SHA256-хеш данной строки и соли</desc>
                    <arg><name>string</name>
                        <type>str</type>
                        <desc>Основная строка</desc>
                    </arg>
                    <arg><name>salt</name>
                        <type>str</type>
                        <desc>Соль</desc>
                    </arg>
                    <ret>str[32]</ret>
                </method>
            </file>
        </folder>
    </folder>
    <folder><path>doc</path>
        <title>Написание документации</title>
        <desc>Инструкция по написанию документации.</desc>
        <folder><path>tags</path>
